### ISSUE TITLE
 Could not pass event MarriedPlayerJoinEvent/PlayerInteractEntityEvent in "normal mode"

### ISSUE THREAD

**Issue by hkkongou** [GeorgH93/MarriageMaster#194]
### Information
**Environment information**
*Plugin + server version info*:

```

[15:32:17 INFO]: ##### Start Marriage Master version info #####
[15:32:17 INFO]: Marriage Master: 2.3.1-Release
[15:32:17 INFO]: PCGF PluginLib: 1.0.32-SNAPSHOT-T20210529224850
[15:32:17 INFO]: Server: git-Purpur-1149 (MC: 1.16.5)
[15:32:17 INFO]: Java: 11.0.10
[15:32:17 INFO]: Vault: 1.7.3-b131
[15:32:17 INFO]: #####  End Marriage Master version info  #####

```

*Online mode*: yes

*BungeeCord*: yes

**Server/crash log**

```

https://gist.github.com/hkkongou/9cd320c807014278044b4f235a5fb973

```

**Plugin config (optional)**

```
marriage master:
https://gist.github.com/hkkongou/4e62c8b632caab78bb16fd61ddd772f9

PCGF pluginlib
https://gist.github.com/hkkongou/ae8c052efbf08c58e97bec5b20ef7d43

```

### Details
**Description**  
i am trying to use mysql set up between servers. so i installed pcgf pluginlib, to make marriage master become normal mode, however with pcgf pluginlib, when i use /marry hug or /marry kiss, it show error message and nothing does, without pcgf pluginlib, in standalone mode, everything works. but without pcgf lib, i cannot sync between server using mysql

**Steps to reproduce**  
1. install pcgflib and marriage master with mysql set up already in config
2. server server
3. use /marry kiss or shift right click

**Expected behavior**  
it should have kiss heart pop up, nothing comes up now

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
i have been running marriage master for a year, and i was using sqlite .db file to store data, if possible, plz provide me a method to import sqlite user marry data to mysql, thank you

**Comment by GeorgH93** [comment]
Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/PluginLib/491/artifact/target/PCGF_PluginLib-1.0.32-SNAPSHOT.jar) of the PluginLib.
MySQL and BungeeCord should also work without the PluginLib (it is bundled with the plugin). The advantages of installing it are only there if you have multiple plugins using it (e.g. Marriage Master and Minepacks on the same server).

Support to migrate from SQLite to MySQL is planned, but I haven't had the time to add it so far.
I have added how you can manually migrate the data in [this issue](https://github.com/GeorgH93/MarriageMaster/issues/83).

**Comment by hkkongou** [comment]
> Should be fixed with [this build](https://ci.pcgamingfreaks.at/job/PluginLib/491/artifact/target/PCGF_PluginLib-1.0.32-SNAPSHOT.jar) of the PluginLib.
> MySQL and BungeeCord should also work without the PluginLib (it is bundled with the plugin). The advantages of installing it are only there if you have multiple plugins using it (e.g. Marriage Master and Minepacks on the same server).
> 
> Support to migrate from SQLite to MySQL is planned, but I haven't had the time to add it so far.
> I have added how you can manually migrate the data in [this issue](https://github.com/GeorgH93/MarriageMaster/issues/83).

sorry i still get error when kiss or hug
https://gist.github.com/hkkongou/a7830047bb3543ffd1af319befd48e6a

btw, may i ask a questions? does marriage master works for mysql sync between multiple server? if yes, do i need to install PCGF in that situation too? i read the wiki but i am not that good in english : (

**Comment by GeorgH93** [comment]
I would recommend you to just drop the PCGF PluginLib for now (you do not need it).

Yes, Marriage Master works fine with MySQL in a multi server setup. Make sure to enable the BungeeCord config option, set the same MySQL database settings on all servers and add the plugin to your BungeeCord server. You do not need the PCGF PluginLib for that.
