### ISSUE TITLE
People can't divorce

### ISSUE THREAD

**Issue by Qinak** [GeorgH93/MarriageMaster#65]
People can't divorce. The money is drawn and the messages get sent but you don't actually get divorced.

**Comment by GeorgH93** [comment]
Thanks for the report. Should be fixed with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/95/artifact/target/MarriageMaster-2.0-RC3-SNAPSHOT.jar

**Comment by Qinak** [comment]
Thanks! With this configured: https://pastebin.com/3xnBrBDi and having `marry.selfdivorce` a player can't divorce when partner is offline

**Comment by GeorgH93** [comment]
I fixed some more bugs around divorcing with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/97/artifact/target/MarriageMaster-2.0-RC3-SNAPSHOT.jar
Will do some more testing this weekend.

**Comment by GeorgH93** [comment]
I think I have found all the bugs with the divorce with this build: https://ci.pcgamingfreaks.at/job/MarriageMaster%20V2/102/artifact/target/MarriageMaster-2.0-RC3-SNAPSHOT.jar

**Comment by Qinak** [comment]
Players still can't self divorce when their partner is offline, but as of now if people need to divorce I can tell them to message me.

**Comment by GeorgH93** [comment]
> 
> 
> Players still can't self divorce when their partner is offline, but as of now if people need to divorce I can tell them to message me.

What message / error is there when they try to divorce?
